project:
  type: website
  output-dir: docs

website:
  title: "The Programming Pages"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "floating"
    contents:
      - section: "Creating your own web page"
        contents:
         - make_web_page.qmd
         - add_pages.qmd
         - customize_webpage.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    grid:
      sidebar-width: 250px
      body-width: 2000px
      margin-width: 100px
      gutter-width: 1rem



