project:
  type: website
  output-dir: docs

website:
  title: "The Programming Pages"
  favicon: pics/logo/Binary_code.png
  navbar:
    right:
      - icon: github
        menu:
          - text: "GitHub repository"
            href: https://github.com/lzapffe/programming-pages
          - text: "Suggest improvements"
            href: https://github.com/lzapffe/programming-pages/issues
          - text: "Contact me"
            icon: chat-text
            href: contact.qmd
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: primary
  sidebar:
    style: "floating"
    contents:
      - section: "Rmarkdown and Quarto"
        contents:
          - rmarkdown_basics.qmd
          - quarto.qmd
      - section: "Creating your own web page"
        contents:
         - make_web_page.qmd
         - add_pages.qmd
         - customize_webpage.qmd
         - track_webpage.qmd
         - troubleshooting.qmd
      - section: "Graphs and Diagrams"
        contents:
         - mermaid.qmd
         - graphviz.qmd
      - section: "Version Control with Git"
      - section: "Miscallenous"
        contents:
          - cool_things.qmd



format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 275px
      body-width: 2000px
      margin-width: 100px
      gutter-width: 1rem
    include-in-header:
      - file: goatcounter.js
      



