project:
  type: website
  output-dir: docs

website:
  title: "The Programming Pages"
  favicon: pics/logo/Binary_code.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: primary
  sidebar:
    style: "floating"
    contents:
      - section: "Creating your own web page"
        contents:
         - make_web_page.qmd
         - add_pages.qmd
         - customize_webpage.qmd
  google-analytics:
    tracking-id: "G-RDKZRGQ180"
  cookie-consent:
    type: express


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    grid:
      sidebar-width: 275px
      body-width: 2000px
      margin-width: 100px
      gutter-width: 1rem
    include-in-header:
      file: header.html



